# Generated by Django 6.0 on 2026-01-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del producto (EAN-13, UPC, Code-128, etc.)', max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
