# Generated by Django 6.0 on 2026-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConocimientoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('meta', 'Meta/Objetivo'), ('preferencia', 'Preferencia'), ('dato_clave', 'Dato Clave'), ('patron', 'Patrón Detectado'), ('estrategia', 'Estrategia Definida')], max_length=20)),
                ('clave', models.CharField(db_index=True, max_length=200)),
                ('valor', models.TextField()),
                ('contexto', models.TextField(blank=True, null=True)),
                ('confianza', models.FloatField(default=1.0)),
                ('aprendido_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gameplay_conocimiento_negocio',
                'ordering': ['-ultima_actualizacion'],
                'unique_together': {('clave',)},
            },
        ),
    ]
