# Generated by Django 6.0 on 2026-01-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_conocimientonegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tendencia_alza', 'Tendencia al Alza'), ('tendencia_baja', 'Tendencia a la Baja'), ('correlacion', 'Correlación entre Productos'), ('anomalia', 'Anomalía Detectada'), ('oportunidad', 'Oportunidad de Negocio'), ('alerta', 'Alerta Importante'), ('estacionalidad', 'Patrón Estacional')], max_length=30)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('recomendacion', models.TextField(blank=True)),
                ('producto_relacionado', models.CharField(blank=True, max_length=200, null=True)),
                ('metrica_valor', models.FloatField(blank=True, null=True)),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gameplay_insight_negocio',
                'ordering': ['-detectado_en'],
            },
        ),
    ]
